force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>N26 Product</label>
    <referenceTo>N26_Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/N26_Product__c.object-meta.xml
<CustomObject>
    <label>N26 Product</label>
    <nameField>
        <label>N26 Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>N26 Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product__c/fields/N26_Product_Description__c.field-meta.xml
<CustomField>
    <fullName>N26_Product_Description__c</fullName>
    <label>N26 Product Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/N26_Product_Detail__c.object-meta.xml
<CustomObject>
    <label>N26 Product Detail</label>
    <nameField>
        <displayFormat>N26-{0000000}</displayFormat>
        <label>N26 Product Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>N26 Product Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product_Detail__c/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/N26_Product__c.field-meta.xml
<CustomField>
    <fullName>N26_Product__c</fullName>
    <label>N26 Product</label>
    <referenceTo>N26_Product__c</referenceTo>
    <relationshipLabel>N26 Product Details</relationshipLabel>
    <relationshipName>N26_Product_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactProductDetailsControllerTest.cls
@isTest
public class ContactProductDetailsControllerTest {

    @TestSetup
    public static void createTestData(){

        N26_Product__c testProduct = new N26_Product__c();
        testProduct.Name = 'Black - Apex Testing Only';
        testProduct.N26_Product_Description__c = 'Black Product Description - Apex Testing Only';
        Database.insert(testProduct);

        N26_Product_Detail__c testProductDetails = new N26_Product_Detail__c();
        testProductDetails.N26_Product__c = testProduct.Id;
        testProductDetails.Country__c = 'DE';
        testProductDetails.Cost_per_Calendar_Month__c = '€ 9,90';
        testProductDetails.Card_Replacement_Cost__c = '€ 6';
        testProductDetails.ATM_Fee_in_other_currencies__c = 'Free';
        Database.insert(testProductDetails);

        Contact testContactRecord = new Contact();
        testContactRecord.FirstName = 'Ms. Testing Apex';
        testContactRecord.LastName = 'Contact';
        testContactRecord.Product__c = testProduct.Id;
        testContactRecord.Home_Country__c = 'DE';
        Database.insert(testContactRecord);

        Case testCaseRecord = new Case();
        testCaseRecord.Subject = 'Test Case';
        testCaseRecord.Status = 'New';
        testCaseRecord.Origin = 'Email';
        testCaseRecord.ContactId = testContactRecord.Id;
        Database.insert(testCaseRecord);
    }

    /*
    * Function: GetProductDetailsTest
    * Purpose:  This test method tests for getting the data succesfully using a proper contactId value
    */
    @isTest
    public static void GetProductDetailsTest() {
        Test.startTest();

        Contact testContactRecord = [SELECT Id FROM Contact WHERE FirstName = 'Ms. Testing Apex' LIMIT 1];
        Case testCaseRecord = [SELECT Id FROM Case WHERE ContactId =: testContactRecord.Id LIMIT 1];

        N26_Product_Detail__c returnedProductDetail = ContactProductDetailsController.getProductDetails(testCaseRecord.Id);
        
        Assert.areNotEqual(null, returnedProductDetail, 'There should have been a Product Detail record returned.');
        Assert.areEqual('DE', returnedProductDetail.Country__c, 'The Product Detail record should have DE as the Country.');

        Test.stopTest();
    }

    /*
    * Function: GetProductDetailsNoProductDetailTest
    * Purpose:  This test method tests the error handling (with no product detail record that exists)
    */
    @isTest
    public static void GetProductDetailsNoProductDetailTest() {
        Test.startTest();
 
        N26_Product__c testProduct = [SELECT Id FROM N26_Product__c WHERE Name = 'Black - Apex Testing Only' LIMIT 1];
        N26_Product_Detail__c testProductDetailRecord = [SELECT Id FROM N26_Product_Detail__c WHERE Country__c = 'DE' AND N26_Product__c =: testProduct.Id LIMIT 1];
        Database.delete(testProductDetailRecord);

        Contact testContactRecord = [SELECT Id FROM Contact WHERE FirstName = 'Ms. Testing Apex' LIMIT 1];
        Case testCaseRecord = [SELECT Id FROM Case WHERE ContactId =: testContactRecord.Id LIMIT 1];

        N26_Product_Detail__c returnedProductDetail = ContactProductDetailsController.getProductDetails(testCaseRecord.Id);
        Assert.areEqual(null, returnedProductDetail, 'There should have been no Product Detail record returned.');  

        Test.stopTest();
    }

    /*
    * Function: GetProductDetailsNoHomeCountryTest
    * Purpose:  This test method tests the error handling (by setting the Home Country on the Contact to empty)
    */
    @isTest
    public static void GetProductDetailsNoHomeCountryTest() {
        Test.startTest();

        Contact testContactRecord = [SELECT Id FROM Contact WHERE FirstName = 'Ms. Testing Apex' LIMIT 1];
        testContactRecord.Home_Country__c = '';
        Database.update(testContactRecord);

        Case testCaseRecord = [SELECT Id FROM Case WHERE ContactId =: testContactRecord.Id LIMIT 1];

        N26_Product_Detail__c returnedProductDetail = ContactProductDetailsController.getProductDetails(testCaseRecord.Id);
        
        Assert.areEqual(null, returnedProductDetail, 'There should have been no Product Detail record returned.');  

        Test.stopTest();
    }
}