force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>N26 Product</label>
    <referenceTo>N26_Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/N26_Product__c/N26_Product__c.object-meta.xml
<CustomObject>
    <label>N26 Product</label>
    <nameField>
        <label>N26 Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>N26 Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product_Detail__c/N26_Product_Detail__c.object-meta.xml
<CustomObject>
    <label>N26 Product Detail</label>
    <nameField>
        <displayFormat>N26-{0000000}</displayFormat>
        <label>N26 Product Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>N26 Product Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product_Detail__c/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/N26_Product__c.field-meta.xml
<CustomField>
    <fullName>N26_Product__c</fullName>
    <label>N26 Product</label>
    <referenceTo>N26_Product__c</referenceTo>
    <relationshipLabel>N26 Product Details</relationshipLabel>
    <relationshipName>N26_Product_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactProductDetailsWebService.cls
@RestResource(urlMapping='/Contact/ProductDetails/*')
global without sharing class ContactProductDetailsWebService {

    /*
    * Function: getProductDetails
    * Purpose:  This function parses the UUID parameters and finds the Product Details related
    * to the Contact
    */
    @HttpGet
    global static void getProductDetails(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        String requestBody = req.requestBody.toString();
        String contactQuery = 'SELECT Id, Product__c, Home_Country__c FROM Contact';
        String productDetailsQuery = 'SELECT Id, N26_Product__c, N26_Product__r.Name, Country__c, Cost_per_Calendar_Month__c, Card_Replacement_Cost__c, ATM_Fee_in_other_currencies__c FROM N26_Product_Detail__c';

        try {
            String uuidParam = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
            
            if(String.isNotBlank(uuidParam)){
                contactQuery += ' WHERE UUID__c=\'' + uuidParam + '\' LIMIT 1';
            } else {
                throw new CustomInvalidException('Invalid Request - UUID was not Provided in the Parameters');
            }

            List<Contact> contactRecordResults = Database.Query(contactQuery);
            if(contactRecordResults.size() == 0){
                throw new CustomNotFoundException('No Contact Record was Found');
            }

            Contact contactRecord = contactRecordResults[0];

            // Query to find the product details
            if(String.isNotBlank(contactRecord.Product__c) && String.isNotBlank(contactRecord.Home_Country__c)){
                productDetailsQuery += ' WHERE N26_Product__c=\'' + contactRecord.Product__c + '\'' + ' AND Country__c=\'' + contactRecord.Home_Country__c + '\' LIMIT 1';
            } else {
                throw new CustomNotFoundException('Unable to Find Product Details - Both Product and Home Country fields must be populated on the Contact');
            }

            List<N26_Product_Detail__c> productDetailsResults = Database.Query(productDetailsQuery);
            if(productDetailsResults.size() == 0){
                throw new CustomNotFoundException('No Product Details Record was Found for this Product and Home Country');
            }

            ContactProductDetailsResponseWrapper.ProductDetail responseBody = new ContactProductDetailsResponseWrapper.ProductDetail();
            res.statusCode = 200;
            res.responseBody = Blob.valueOf(buildProductDetailsResponse(responseBody, productDetailsResults[0]));
        } catch(CustomNotFoundException e){
            res.statusCode = 404;
            ContactProductDetailsUtil.buildErrorResponse(e, res, 'Not Found');
        } catch(CustomInvalidException e){
            res.statusCode = 400;
            ContactProductDetailsUtil.buildErrorResponse(e, res, 'Invalid Request');
        } catch(Exception e){
            ContactProductDetailsUtil.buildErrorResponse(e, res, 'Exception');
        }
    }

    /*
    * Function: buildProductDetailsResponse
    * Purpose:  This Helper function builds up the 200 OK JSON Response for the Product Details HttpGet Method
    */
    public static String buildProductDetailsResponse(ContactProductDetailsResponseWrapper.ProductDetail responseBody, N26_Product_Detail__c productDetailsResults){        
        responseBody.homeCountry = productDetailsResults.Country__c;
        responseBody.productName = productDetailsResults.N26_Product__r.Name;
        responseBody.atmFee = productDetailsResults.ATM_Fee_in_other_currencies__c;
        responseBody.cardReplacementCost = productDetailsResults.Card_Replacement_Cost__c;
        responseBody.costPerCalendarMonth = productDetailsResults.Cost_per_Calendar_Month__c;

        return JSON.serialize(responseBody);
    }

    public class CustomInvalidException extends Exception {}
    public class CustomNotFoundException extends Exception {}

}