force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>N26 Product</label>
    <referenceTo>N26_Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/N26_Product__c/N26_Product__c.object-meta.xml
<CustomObject>
    <label>N26 Product</label>
    <nameField>
        <label>N26 Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>N26 Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product_Detail__c/N26_Product_Detail__c.object-meta.xml
<CustomObject>
    <label>N26 Product Detail</label>
    <nameField>
        <displayFormat>N26-{0000000}</displayFormat>
        <label>N26 Product Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>N26 Product Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/N26_Product_Detail__c/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/N26_Product_Detail__c/fields/N26_Product__c.field-meta.xml
<CustomField>
    <fullName>N26_Product__c</fullName>
    <label>N26 Product</label>
    <referenceTo>N26_Product__c</referenceTo>
    <relationshipLabel>N26 Product Details</relationshipLabel>
    <relationshipName>N26_Product_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactProductDetailsController.cls
public without sharing class ContactProductDetailsController {

    /* Function: getProductDetails
    *  Purpose: This function is to get the product details depending on the Product and Home Country
    *  of the Contact record related to the current Case.
    */
    @AuraEnabled(cacheable=true)
    public static N26_Product_Detail__c getProductDetails(Id caseRecordId){
        System.debug('caseRecordId >> ' + caseRecordId);
        if(caseRecordId != null){
            Case caseRecord = [SELECT Id, ContactId, Contact.Name, Contact.Product__c, Contact.Home_Country__c FROM Case WHERE Id = :caseRecordId LIMIT 1];
            Id productId = caseRecord.Contact.Product__c;
            String homeCountry = caseRecord.Contact.Home_Country__c;
            System.debug('productId >> ' + productId);

            N26_Product_Detail__c productDetails = [SELECT Id, ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c, Cost_per_Calendar_Month__c, N26_Product__c, N26_Product__r.Name, Country__c FROM N26_Product_Detail__c WHERE Country__c =: homeCountry AND N26_Product__c =: productId LIMIT 1];
            if(productDetails != null){
                return productDetails;
            } else {
                return null;
            }
        } else {
            return null;
        }
    }

    // on the case record
    // will have the contact id
    // get the Product__ and Home_Country__c from the contact record
    // then query the N26_Product_Detail__c table for the key pair value
    // use try catch methods
}